before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: gitstat
    goos:
      - linux
      - windows
    goarch:
      - amd64
  - id: gitstat-macos
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon gon.hcl # Sign binary with Developer ID Application certificate
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
